version: "3.8"

services:
  fastapi-service:
    build: .
    container_name: fastapi-bot
    ports:
      - "5000:5000"  # Проброс порта 5000
    restart: unless-stopped
    environment:
      - TZ=UTC
    volumes:
      - ./logs:/app/logs
    # runtime: nvidia
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]