version: "3.8"

services:
  fastapi-service:
    build: .
    container_name: fastapi-bot
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - TZ=UTC
    volumes:
      - ./logs:/app/logs
